1. SELECT city.name, country.name FROM country JOIN city ON country.code = city.countrycode;
2. SELECT country.continent, city.name, city.population FROM country JOIN city ON country.code = city.countrycode WHERE country.name = "Germany";
3. SELECT country.name, city.name FROM country JOIN city ON country.capital = city.id ORDER BY country.name;
4. SELECT country.name, countylanguage.language FROM country JOIN countrylanguage ON country.code = countrylanguage.countrycode WHERE countrylanguage.isofficial = "T";
5. SELECT country.name, COUNT(countrylanguage.language) AS number_of_language from country join countrylanguage on country.code = countrylanguage.countrycode GROUP BY country.name ORDER BY number_of_language DESC;
6. SELECT country.continent, country.name, city.population FROM country JOIN city on country.capital = city.id ORDER BY population DESC LIMIT 5;
7. SELECT country.continent, country.name, city.name, city.population FROM country JOIN city ON country.code = city.countrycode WHERE country.continent = "South America";
8.  SELECT country.name, country.population, countrylanguage.language FROM country JOIN countrylanguage ON country.code = countrylanguage.countrycode ORDER BY country.name, countrylanguage.language;
9.SELECT country.name AS name_of_country, country.population AS total_population, COUNT(countrylanguage.language) AS number_of_languages FROM country JOIN countrylanguage ON country.code = countrylanguage.countrycode GROUP BY country.name, country.population ORDER BY number_of_languages;
10. SELECT country.name, city.name, countrylanguage.language FROM country JOIN city ON country.capital = city.id JOIN countrylanguage ON country.code = countrylanguage.countrycode WHERE countrylanguage.isofficial = "T" AND countrylanguage.language = "FRENCH";
11. SELECT country.continent, COUNT(city.id) AS number_of_city FROM country JOIN city ON country.capital = city.id GROUP BY country.continent;
12. SELECT country.name, AVG(city.population) FROM country JOIN city ON country.code = city.countrycode GROUP BY country.name;
13. SELECT country.continent, country.population from country ORDER BY population DESC LIMIT 1;
14. SELECT country.name AS name_of_country, COUNT(countrylanguage.language) AS number_of_language FROM country JOIN countrylanguage ON country.code = countrylanguage.countrycode GROUP BY country.name HAVING number_of_language > 5;
15. SELECT country.name, city.name, city.population FROM country JOIN city ON country.capital = city.id ORDER BY city.population DESC LIMIT 10;
16.  SELECT country.name, COUNT(city.id) FROM city JOIN country ON country.code = city.countrycode WHERE city.population > 1000000 GROUP BY country.name;
17. SELECT country.continent, city.name, city.population FROM country JOIN city ON country.code = city.countrycode WHERE city.population = (SELECT MAX(c2.population) FROM city c2 JOIN country co2 ON c2.countrycode = co2.code WHERE co2.continent = country.continent);
18.  SELECT language, COUNT(DISTINCT countrycode) AS country_count FROM countrylanguage GROUP BY language HAVING country_count > 10;
19. SELECT country.name, city.name, countrylanguage.language FROM country JOIN city ON country.capital = city.id JOIN countrylanguage ON country.code = countrylanguage.countrycode WHERE countrylanguage.isofficial = "F" ORDER BY country.name, countrylanguage.language;
20. SELECT country.name, country.continent, city.name FROM country JOIN city ON country.capital = city.id JOIN countrylanguage ON country.code = countrylanguage.countrycode WHERE countrylanguage.language = "English";
21. SELECT country.name, COUNT(DISTINCT countrylanguage.language) AS count_of_language FROM country JOIN countrylanguage ON country.code = countrylanguage.countrycode GROUP BY country.name;
22. SELECT country.name, city.name, city.population FROM country JOIN city ON country.capital = city.id WHERE country.continent = "Asia";
23.SELECT country.continent, country.name, city.name, city.population FROM country JOIN city ON country.capital = city.id WHERE city.population > 2000000;
24. SELECT country.name, country.region, city.name FROM country JOIN city ON country.capital = city.id JOIN countrylanguage ON country.code = countrylanguage.countrycode WHERE countrylanguage.language = "Spanish";
25. SELECT country.name, city.name, city.population FROM country JOIN city ON country.capital = city.id ORDER BY city.population DESC;
26. SELECT country.name, city.name, countrylanguage.language FROM country JOIN city ON country.capital = city.id JOIN countrylanguage ON country.code = countrylanguage.countrycode WHERE countrylanguage.isofficial = "T" AND country.continent = "Europe";
27. SELECT country.name, country.population, city.name, city.population FROM country JOIN city ON country.capital = city.id;
28. SELECT country.name, city.name, city.population FROM country JOIN city ON country.capital = city.id WHERE city.population < 0.05 * country.population;
29.SELECT c.name AS country_name, c.region AS region_name, ct.name AS city_name, ct.population FROM country c JOIN city ct ON ct.countrycode = c.code WHERE ct.population = (SELECT MAX(ct2.population) FROM city ct2 WHERE ct2.countrycode = c.code)ORDER BY c.name, c.region;
30. SELECT country.continent, city.name AS city_name, city.population FROM city JOIN country ON city.countrycode = country.code WHERE city.population = (SELECT MAX(c2.population) FROM city c2 JOIN country co2 ON c2.countrycode = co2.code WHERE co2.continent = country.continent) ORDER BY country.continent, city.population DESC;
31. SELECT country.name FROM country JOIN city ON country.capital = city.id WHERE city.population > 0.5 * country.population;
32. SELECT countrylanguage.language FROM countrylanguage JOIN country ON countrylanguage.countrycode = country.code WHERE country.name = ( SELECT name FROM country ORDER BY lifeexpectancy DESC LIMIT 1) AND countrylanguage.isofficial = 'T';